# Site settings
title: Learnings in game development
email: mikeyjc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple blog that will cover some of the things I've learned in C# and
  what I try to figure out while building games in unity
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://coop.codes" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mijcooper
github_username:  scoutski

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
